ccd_swc/ccd_swc/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from room import views
from django.contrib.auth import views as v

urlpatterns = [
    path('',views.about,name='about'),
    path('admin/', admin.site.urls),
    path('',include("room.urls")),
    path('accounts/login/', v.LoginView.as_view(), name='login'),
    path('accounts/logout/', v.LogoutView.as_view(), name='logout'),
]
if settings.DEBUG:
    import debug_toolbar
    urlpatterns = [
        path('__debug__/',include(debug_toolbar.urls)),
    ] + urlpatterns

ccd_swc/room/urls.py
from django.urls import path
from . import views

app_name = 'room'

urlpatterns = [
    path('all_data/', views.export, name='export_data'),

    path('company/', views.export_company, name='export_company'),

    path('index/', views.search, name='index'),

	path('<int:pk>/', views.DetailView.as_view(), name='detail'),

    path('barak_room_list/',views.barak_room_list.as_view(),name='barak_room_list'),

    path('umiam_room_list/',views.umiam_room_list.as_view(),name='umiam_room_list'),

    path('<int:pk>/barak',views.room_list,name='roomlist'),

    path('<int:pk>/umiam',views.room_list1,name='roomlist1'),

	path('add_company/', views.CompanyCreate.as_view(), name='company-add'),

	path('<int:pk>/company_update', views.CompanyUpdate.as_view(), name='company-update'),

	path('<int:pk>/company_delete/', views.CompanyDelete.as_view(), name='company-delete'),

    path('<int:pk>/barak/delete_room/', views.remove_room, name='room_remove'),

    path('<int:pk>/barak/add_rooms',views.add_room,name='roomadd'),

    path('<int:pk>/umiam/delete_room/', views.remove_room1, name='room_remove1'),

    path('<int:pk>/umiam/add_rooms',views.add_room1,name='roomadd1'),

    path('delete_all_rooms/',views.addrooms_delete,name='rooms_delete'),

]

ccd_swc/room/models.py
from django.db import models
from django.urls import reverse
from django.core.exceptions import ValidationError
from django.core.validators import RegexValidator

class Company(models.Model):
	name = models.CharField(max_length=250)
	industry = models.CharField(max_length=250)
	poc = models.CharField(max_length=250)

	class Meta:
		verbose_name = "Companie"

	def get_absolute_url(self):
		return reverse('room:detail', kwargs={'pk': self.pk})

	def __str__(self):
		return self.name

	def get_photo_url(self):
		if self.logo and hasattr(self.logo, 'url'):
			print("YES")
			return self.logo.url
		else:
			print("NO")
			return "media/company_logo/user.jpg"

class Hostel(models.Model):
	name = models.CharField(max_length=100)

	class Meta:
		verbose_name = "Hostel"

	def __str__(self):
		return self.name

class Room(models.Model):
	company = models.ForeignKey(Company,related_name="rooms",on_delete=models.CASCADE)
	hostel = models.ForeignKey(Hostel,on_delete=models.SET_NULL,null=True)
	room_no = models.CharField(max_length=100,validators=[
        RegexValidator(
			regex='^([A-Z])-([0-9])+$',
            message='room number must be of form: A-9'
        ),
    ])

	class Meta:
		verbose_name = "Room"
		unique_together = ['room_no','hostel']

	def company_fill(self,Company):
		self.company = Company.pk
	def save(self,*args, **kw):
		super(Room,self).save(*args, **kw)
	def __str__(self):
		return self.room_no

class data(models.Model):
	room_no = models.CharField(max_length=100,validators=[
        RegexValidator(
			regex='^([A-Z])-([0-9])+$',
            message='room number must be of form: A-9'
        ),
    ])

	class Meta:
		verbose_name = "Data Set"

	hostel  = models.CharField(max_length=100)
	company = models.CharField(max_length=250)

ccd_swc/room/forms.py
from django import forms
from .models import Company, Room
from django.contrib.auth.models import User

class RoomForm(forms.ModelForm):
    class Meta:
        model = Room
        fields = ('room_no',)

class FilebabyForm(forms.ModelForm):
    class Meta:
        model = Company
        fields = ('name', 'industry', 'poc')

    widgets = {
            'name': forms.TextInput(attrs={'class': ''}),
            'industry': forms.Textarea(attrs={'class': ''}),
            'poc': forms.TextInput(attrs={'class': ''}),
        }

class UserForm(forms.ModelForm):
    password = forms.CharField(widget=forms.PasswordInput())
    class Meta():
        model = User
        fields = ('username','email','password')

ccd_swc/room/views.py
from django.shortcuts import render, get_object_or_404, redirect
from django.views.generic.edit import  CreateView, UpdateView, DeleteView, FormView
from django.views.generic import TemplateView
from django.urls import reverse_lazy
from django.shortcuts import render, redirect
from django.contrib.auth import authenticate, login
from django.views import generic
from django.views.generic import View
from .models import Company, Hostel, Room, data
from .forms import FilebabyForm,RoomForm
from django import forms
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin
from django.http import HttpResponse
from .resources import CompanyResource, dataResource
import sqlite3

class barak_room_list(TemplateView):
	template_name = 'room_list.html'
	def get(self,request):
		s = Hostel.objects.filter(name="Barak")
		ro = Room.objects.filter(hostel=s[0])
		return render(request,self.template_name,{'roomlist':ro,'hostel':'Barak'})

class umiam_room_list(TemplateView):
	template_name = 'room_list.html'
	def get(self,request):
		s = Hostel.objects.filter(name="Umiam")
		ro = Room.objects.filter(hostel=s[0])
		return render(request,self.template_name,{'roomlist':ro,'hostel':'Umiam'})

def export_company(request):
	company_resource = CompanyResource()
	dataset = company_resource.export()
	response = HttpResponse(dataset.csv, content_type='text/csv')
	response['Content-Disposition'] = 'attachment; filename="companies.csv"'
	return response

def export(request):
	for room in Room.objects.all():
		data.objects.create(company=room.company.name,hostel=room.hostel.name,room_no=room.room_no)
	data_resource = dataResource()
	dataset = data_resource.export()
	response = HttpResponse(dataset.csv, content_type='text/csv')
	response['Content-Disposition'] = 'attachment; filename="all_data.csv"'
	data.objects.all().delete()
	return response

class DetailView(generic.DetailView):
	template_name = 'company_detail.html'
	model = Company

def addrooms_delete(request):
	results = Company.objects.all()
	if request.method == 'POST':
		Room.objects.all().delete()
		return render(request,'company_list.html',{'data':results})
	else:
		return render(request,'allrooms_confirm_delete.html')

def room_list(request,pk):
	company = get_object_or_404(Company,pk=pk)
	s = Hostel.objects.filter(name="Barak")
	ro = Room.objects.filter(hostel=s[0])
	return render(request,'company_roomlist.html',{'roomlist':ro,'hostel':"Barak",'company':company.name})

def room_list1(request,pk):
	company = get_object_or_404(Company,pk=pk)
	s = Hostel.objects.filter(name="Umiam")
	ro = Room.objects.filter(hostel=s[0])
	return render(request,'company_roomlist.html',{'roomlist':ro,'hostel':"Umiam",'company':company.name})

def search(request):
	query = request.GET.get('q','')
	if query:
		results = Company.objects.filter(name__istartswith=query)
	else:
		results = Company.objects.all()
	return render(request, 'company_list.html', {'data':results})

def add_room(request,pk):
	company = get_object_or_404(Company,pk=pk)
	s = Hostel.objects.filter(name="Barak")
	ro = Room.objects.filter(hostel=s[0])

	if request.method == "POST":
		rooms = request.POST['roo']
		l = rooms.split()
		for room in l:
			Room.objects.create(company=company,hostel=s[0],room_no=room)
		return redirect('room:detail', pk=company.pk)
	else:
		form = RoomForm()
	return render(request,'add_room.html',{'form':form,'primary':pk,'rooms':ro})

@login_required
def remove_room(request,pk):
	comp = get_object_or_404(Company,pk=pk)
	if request.method == 'POST':
		form = RoomForm(request.POST)
		room = request.POST.get('room_no')
		k = Hostel.objects.filter(name="Barak")
		dk = Room.objects.filter(company=comp,hostel=k[0],room_no=room)
		if not dk:
			return HttpResponse("<h1 style='text-align:center;margin-top:20px;'>Room Number " + room + " is not alloted to " + comp.name + " in " + "Barak Hostel</h1>")
		dk.delete()
		return redirect('room:detail', pk=comp.pk)
	else:
		form = RoomForm()
	return render(request,'room_delete.html',context={'form':form})


def add_room1(request,pk):
	company = get_object_or_404(Company,pk=pk)
	s = Hostel.objects.filter(name="Umiam")
	ro = Room.objects.filter(hostel=s[0])

	if request.method == "POST":
		rooms = request.POST['roo']
		l = rooms.split()
		for room in l:
			Room.objects.create(company=company,hostel=s[0],room_no=room)
		return redirect('room:detail', pk=company.pk)
	else:
		form = RoomForm()
	return render(request,'add_room1.html',{'form':form,'primary':pk,'rooms':ro})

def remove_room1(request,pk):
	comp = get_object_or_404(Company,pk=pk)
	if request.method == 'POST':
		form = RoomForm(request.POST)
		room = request.POST.get('room_no')
		k = Hostel.objects.filter(name="Umiam")
		dk = Room.objects.filter(company=comp,hostel=k[0],room_no=room)
		if not dk:
			return HttpResponse("<h1 style='text-align:center;margin-top:20px;'>Room Number " + room + " is not alloted to "
			+ comp.name + " in " + "Umiam Hostel</h1>")
		dk.delete()
		return redirect('room:detail', pk=comp.pk)
	else:
		form = RoomForm()
	return render(request,'room_delete1.html',context={'form':form})

class CompanyCreate(LoginRequiredMixin,CreateView):
	login_url = '/login/'
	template_name = 'companycreate.html'
	model = Company
	fields = ('name', 'industry', 'poc')
	success_url = reverse_lazy('room:index')

class CompanyUpdate(LoginRequiredMixin,UpdateView):
	login_url = '/login/'
	template_name = 'companycreate.html'
	model = Company
	fields = ('name', 'industry', 'poc')

class CompanyDelete(LoginRequiredMixin,DeleteView):
	login_url = '/login/'
	model = Company
	success_url = reverse_lazy('room:index')

def about(request):
    return render(request,'about.html',context=None)

ccd_swc/room/templates/about.html
<!DOCTYPE html>
{% load static %}
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <title>HOME</title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static "style.css" %}">
  </head>
  <body>
    <div class="jumbotron">
      <h1 class="feel"><strong>CCD PORTAL</strong></h1>
      <a style="padding:0px 0px 0px 40px;" href="{% url 'room:index' %}">CCD Room Allotment</a>
    </div>

  </body>
</html>

ccd_swc/room/templates/allrooms_confirm_delete.html
{% extends "base.html" %}
{% block body %}
<br>
<br>
<br>
<style>
  a
  {
    color:white;
  }
  body
  {

    background-image:url("https://miro.medium.com/max/1080/1*hU0QQDiOnsKpX4qlIyn_4w.jpeg");
    height:100%;
    background-repeat: no-repeat;
    background-size: cover;
  }
  h1
  {
    color:white;
    padding-bottom:15px;
  }
  .container
  {
    margin : 20px;
    padding-left: 20px;
    padding-right: 20px;
    padding-top: 10px;
    padding-bottom:20px;
    border-radius:30px;
    text-align:left;
    border: 2px solid red;
    width:500px;
    background-color:rgba(255,255,255,0.2);
    transition : all ease 0.7s;
  }
  .container:hover
  {
    background-color:rgba(255,255,255,0.6);
    transition : all ease 0.7s;
  }
</style>
<div class = "container">
<h1>Confirm Delete All Rooms</h1>
<form method="post">
  {% csrf_token %}
  <input onclick="location.href='{% url 'room:index' %}'" type="submit" class="btn btn-danger" value="Confirm">
  <button class = "btn btn-info"><a href="{% url 'room:index' %} ">Cancel</a></button>
</form>
</div>
{% endblock %}

ccd_swc/room/templates/company_detail.html
{% extends 'base.html' %}
{% load staticfiles %}
{{% block title %}
  Company Details
{% endblock %}

{% block body %}
<style>

  body {
      background: linear-gradient(45deg, rgb(240,200,215), rgb(200,200,70), rgb(70,250,200), rgb(250,050,200));
      background-size: 200% 200%;
      animation: gradient 10s ease infinite;
    }
  @keyframes gradient {
    0% {
      background-position: 0% 50%;
    }
    50% {
    background-position: 100% 50%;
    }
    100% {
    background-position: 0% 50%;
    }

    }
    .jumbotron
    {
      padding:8px 15px 15px 15px;
      margin:30px 20px;
      text-align:center;
      border-radius:30px;
      background-color:rgba(255,255,255,0.35);
      border:2px solid rgba(0,0,0,0.7);
      transition:  0.7s ease;
    }
    .container-fluid
    {
      background-color:transparent;
    }
    .row1
    {
        margin-left: auto;
    margin-right: auto;
       width:45%;
       background-color:transparent;
    }
    .panel-body
    {
      margin:0;
      padding:20px;
      border-radius:30px;
      border :5px solid black;
      text-align:center;
      font-family: Tahoma, Verdana, Segoe, sans-serif;
      background-color:rgba(255,255,255,0.40);
      transition:  0.7s ease;
    }
    .panel-body:hover
    {
      background-color:rgba(255,255,255,0.80);
      transition-timing-function: linear;
      transition:  0.7s ease;

    }
    .jumbotron:hover
    {
      background-color:rgba(255,255,255,0.90);
      transition-timing-function: linear;
      transition:  0.7s ease;
    }
    .place
    {
      font-size:45px;
      font-weight:bold;
    }
    .pla
    {
      font-size:35px;
      font-weight:bold;
    }
    h3
    {
      font-size:25px;
    }
    input
    {
      width:250px;
      margin:5px;
    }
    #load
    {
      opacity:1;
    background-color:blue;
    position:fixed;
    width:100%;
    height:100%;
    top:0px;
    left:0px;
    z-index:1000;
    visibility:hidden;
    }
    body, html {
    height: 100%;
    text-align: center;
  }

  body {
  /* background-color: #242F3F; */
  }

  .loader {
  display: inline-block;
  width: 30px;
  height: 30px;
  position: relative;
  border: 4px solid #Fff;
  top: 50%;
  animation: loader 2s infinite ease;
  }

  .loader-inner {
  vertical-align: top;
  display: inline-block;
  width: 100%;
  background-color: #fff;
  animation: loader-inner 2s infinite ease-in;
  }

  @keyframes loader {
  0% {
    transform: rotate(0deg);
  }

  25% {
    transform: rotate(180deg);
  }

  50% {
    transform: rotate(180deg);
  }

  75% {
    transform: rotate(360deg);
  }

  100% {
    transform: rotate(360deg);
  }
  }

  @keyframes loader-inner {
  0% {
    height: 0%;
  }

  25% {
    height: 0%;
  }

  50% {
    height: 100%;
  }

  75% {
    height: 100%;
  }

  100% {
    height: 0%;
  }
  }
</style>

<div id = "load"><span class="loader"><span class="loader-inner"></span></span></div>
<br>
<br>
<br>
<div class="container-fluid">
<div class="row1">
<div class="">

<div class="panel-body">
<h2 class="place">Company: {{ company.name }}</h2>
<h2 class="pla">Industry: {{ company.industry }}</h2>
            <h3>POC: {{ company.poc }}</h3>
            {% if user.is_authenticated %}
            <input onclick = "location.href='{% url 'room:company-update' pk=company.pk %}'" type="button" class="btn btn-warning" value="Update">
            {% endif %}
</div>

</div>
    </div>
  </div>
<br>
  <div class="jumbotron .col-sm-3">
    <h2 class = "pla">Barak</h2>
    <input onclick="location.href='{% url 'room:roomlist' pk=company.pk %}'" type="button" class="btn btn-success" value="Company Room List">
    {% if user.is_authenticated %}
    <input onclick="location.href='{% url 'room:roomadd' pk=company.pk %}'" type="button" class="btn btn-primary" value="Add Room">
    <input onclick="location.href='{% url 'room:room_remove' pk=company.pk %}'" type="button" class="btn btn-danger" value="Delete Room">
    {% endif %}
  </div>

  <div class="jumbotron .col-sm-3">
    <h2 class = "pla">Umiam</h2>
    <input onclick="location.href='{% url 'room:roomlist1' pk=company.pk %}'" type="button" class="btn btn-success" value="Company Room List">
    {% if user.is_authenticated %}
    <input onclick="location.href='{% url 'room:roomadd1' pk=company.pk %}'" type="button" class="btn btn-primary" value="Add Room">
    <input onclick="location.href='{% url 'room:room_remove1' pk=company.pk %}'" type="button" class="btn btn-danger" value="Delete Room">
    {% endif %}
  </div>
  <script>
    $('input').click(function(){
      $('#load').css("visibility","visible");
    });
    window.addEventListener( "pageshow", function ( event )
    {
      var historyTraversal = event.persisted || (typeof window.performance != "undefined" && window.performance.navigation.type === 2);
      if( historyTraversal )
      {
        window.location.reload();
      }
    });
  </script>

  {% endblock %}

ccd_swc/room/templates/company_list.html
{% extends 'base.html' %}
{% load staticfiles %}
{% block title %} CCD Room Allotment {% endblock %}

{% block navigation %}
{% endblock %}

{% block body %}
<style>

.container
{
  text-align:center;
}
*
{
    outline: none;
}

html, body
{
    height: 100%;
    min-height: 100%;
}

body
{
    margin: 0;
}
body {
  background: linear-gradient(rgba(255,255,255,0.3), rgba(255,255,255,0.3)),url("https://upload.wikimedia.org/wikipedia/commons/2/27/IIT_Guwahati.jpg") no-repeat center center fixed;
  -webkit-background-size: cover;
  -moz-background-size: cover;
  -o-background-size: cover;
  background-size: cover;
}

.tb
{
    display: table;
    width: 100%;
}

.td
{
    display: table-cell;
    vertical-align: middle;
}

input, button
{
    color: #fff;
    font-family: Nunito;
    padding: 0;
    margin: 0;
    border: 0;
    background-color: transparent;
}

#cover
{
    position: absolute;
    top:0;
    width: 52%;
    padding: 0px;
    margin-top: 415px;
    margin-left: 42%;
    background-color: black;
    border-radius: 15px;
    box-shadow: 0 5px 50px lightblue, 0 0 0 10px white;
    transform: scale(0.6);
    scale: 0.6;
}
@-moz-document url-prefix()
            {
              #cover
              {
                  position: absolute;
                  top:0;
                  width: 70%;
                  padding: 0px;
                  margin-top: 189px;
                  margin-left: 35%;
                  background-color: black;
                  border-radius: 15px;
                  box-shadow: 0 5px 50px lightblue, 0 0 0 10px white;
                  transform: scale(0.6);
                  scale: 0.6;
                  height:90px;
              }
            }
form
{
    height: 110px;
}

input[type="text"]
{
   padding-left:15px;
    width: 100%;
    height: 92px;
    font-size: 85px;
    line-height: 1.5;
}

input[type="text"]::placeholder
{
    color: grey;
    font-size: 65px;
    padding-left:20px;
}
#pad input
{
   background-color:rgba(0,0,0,0.50);
}
#s-cover
{
    width: 1px;
    padding-left: 35px;
}

button
{
    position: relative;
    display: block;
    width: 84px;
    height: 96px;
    cursor: pointer;
}

#s-circle
{
    position: relative;
    top: -8px;
    left: 0;
    width: 65px;
    height: 65px;
    margin-top: 0;
    border-width: 15px;
    border: 15px solid #fff;
    background-color: transparent;
    border-radius: 50%;
    transition: 0.5s ease all;
}
list
{
  text-align:center;
}
button span
{
    position: absolute;
    top: 68px;
    left: 43px;
    display: block;
    width: 45px;
    height: 15px;
    background-color: transparent;
    border-radius: 10px;
    transform: rotateZ(52deg);
    transition: 0.5s ease all;
}

button span:before, button span:after
{
    content: '';
    position: absolute;
    bottom: 0;
    right: 0;
    width: 45px;
    height: 15px;
    background-color: #fff;
    border-radius: 10px;
    transform: rotateZ(0);
    transition: 0.5s ease all;
}

#s-cover:hover #s-circle
{
    top: -1px;
    width: 67px;
    height: 15px;
    border-width: 0;
    background-color: #fff;
    border-radius: 20px;
}

#s-cover:hover span
{
    top: 50%;
    left: 56px;
    width: 25px;
    margin-top: -9px;
    transform: rotateZ(0);
}

body {
  font-family: 'Open Sans', sans-serif;
  font-weight: 300;
  line-height: 1.42em;
  color:#a7a1ae;
  background-color:#1F2739;
}

h1 {
  font-size:3em;
  font-weight: 300;
  font-size:52px;
  line-height:1em;
  text-align: center;
  color: black;
  font-family:'candara';
}

h2 {
  font-size:1em;
  font-weight: 300;
  text-align: center;
  display: block;
  line-height:1em;
  padding-bottom: 2em;
  color: #FB667A;
}

h2 a {
  font-weight: 700;
  text-transform: uppercase;
  color: #FB667A;
  text-decoration: none;
}

.blue { color: #185875; }
.yellow { color: #FFF842; }

.container th h1 {
 font-weight: bold;
 font-size: 1em;
  text-align: left;
  color: linen;
}

.container td {
 font-weight: normal;
 font-size: 1em;
  webkit-box-shadow: 0 2px 2px -2px #0E1119;
  -moz-box-shadow: 0 2px 2px -2px #0E1119;
       box-shadow: 0 2px 2px -2px #0E1119;
}

.container {
 text-align: center;
 overflow: hidden;
 width: 70%;
 margin: 0 auto;
  display: table;
  padding: 0 0 0 0;
}

.container td, .container th {
 padding-bottom: 2%;
 padding-top: 2%;
  padding-left:2%;
}

/* Background-color of the odd rows */
.container tr{
    background-color: rgba(0,0,0,0.75);
}


.container th {
    background-color: rgba(0,0,0,0.10);
}

.container td:first-child { color: #FB667A; }

.container tr:hover {
    background-color: rgba(0,0,0,0.45);
-webkit-box-shadow: 0 2px 2px -2px #0E1119;
  -moz-box-shadow: 0 2px 2px -2px #0E1119;
       box-shadow: 0 2px 2px -2px #0E1119;
}

.container td:hover {
  background-color: rgba(255,165,0,0.85);
  color: black;


  box-shadow: red -1px 1px, red -2px 2px;
  transform: translate3d(2px, -2px, 0);

  transition-delay: 0s;
transition-duration: 0.25s;
transition-property: all;
  transition-timing-function: line;
}

body
{
  font-family: 'Lucida Sans Unicode';font-size: 25px;
}
#list
{
  text-align:center;
}
#s-cover:hover button span:before
{
    bottom: 11px;
    transform: rotateZ(52deg);
}

#s-cover:hover button span:after
{
    bottom: -11px;
    transform: rotateZ(-52deg);
}
#s-cover:hover button span:before, #s-cover:hover button span:after
{
    right: -6px;
    width: 40px;
    background-color: #fff;
}
#cover{
    zoom: 0.5;
    -moz-transform: scale(0.65);
}
#del
{

  text-align :center;

  background-color: transparent;
}
#cont
{
  /*margin :0 auto;*/

  text-align :center;

  background-color: transparent;
}
.pad
{
  margin : 0px ;
}

#haha
{
  text-align:center;
}
.abc
{
  border:1.5px solid white;
  border-radius:5px;
  padding : 10px;
  margin : 5px;
}
#pad
{
  text-align:center;
  margin:0 auto;
  padding:10px;
}
#pad input:hover
{
  background-color:rgba(0,0,0,0.8);
  transition: background-color 0.3s ease;
}
#cunn:hover
{
  background-color:rgba(255,0,0,0.75);
}
  #load
  {
    opacity:1;
  background-color:blue;
  position:fixed;
  width:100%;
  height:100%;
  top:0px;
  left:0px;
  z-index:1000;
  visibility:hidden;
  }
  body, html
  {
  height: 100%;
  text-align: center;
  }

body {
background-color: #242F3F;
}

.loader {
display: inline-block;
width: 30px;
height: 30px;
position: relative;
border: 4px solid #Fff;
top: 50%;
animation: loader 2s infinite ease;
}

.loader-inner {
vertical-align: top;
display: inline-block;
width: 100%;
background-color: #fff;
animation: loader-inner 2s infinite ease-in;
}

@keyframes loader {
0% {
  transform: rotate(0deg);
}

25% {
  transform: rotate(180deg);
}

50% {
  transform: rotate(180deg);
}

75% {
  transform: rotate(360deg);
}

100% {
  transform: rotate(360deg);
}
}

@keyframes loader-inner {
0% {
  height: 0%;
}

25% {
  height: 0%;
}

50% {
  height: 100%;
}

75% {
  height: 100%;
}

100% {
  height: 0%;
}
}
</style>

<div id = "load"><span class="loader"><span class="loader-inner"></span></span></div>

  <div id="cover">
    <form method="GET" action="." role = "search">
      <div class="tb">
        <div class="td"><input id = "pop" type="text" name="q" placeholder="Search Company Name" required></div>
        <div class="td" id="s-cover">
          <button type="submit" id = "popp" value = "{{query|escape}}">
            <div id="s-circle"></div>
            <span></span>
          </button>
        </div>
      </div>
    </form>
  </div>

  <br>
  <div class = container>
  <h1 class="list"><strong>Company List</strong></h1>
  <div id ="poi">
    <br>
  </div>
  <table  class="table table-hover" border = "3">
    <thead>
        <tr>
        <th>Company Name</th>
        {% if user.is_authenticated %}
        <th id = "haha"><div>Delete</div></th>
        {% endif %}
        </tr>
    </thead>
    <tbody>
    {% for company in data %}
      <tr>
        <td id = "cun"><div id = "cont"><a href="{% url 'room:detail' company.id %}">{{ company.name }}</a></div></td>
        {% if user.is_authenticated %}
        <td id = "cunn">
          <form action="{% url 'room:company-delete' company.id %}" method="post" style="display: inline;">
            {% csrf_token %}
            <input type="submit" value="Delete">
          </form>
        </td>
        {% endif %}
      </tr>
    </tbody>
    {% endfor %}
  </table>
  </div>

  <br>
  <div id="pad">

    <input id = 'f1' type="button" class="abc" value="Barak Room List">
    <input id = 'f2' type="button" class="abc" value="Umiam Room List">
    {% if user.is_authenticated %}
    <input onclick="location.href='{% url 'room:rooms_delete' %}'" type="button" class="abc" value="Delete All Rooms">
    <input onclick="location.href='{% url 'room:export_company' %}'" type="button" class="abc" value="Export Companies">
    <input onclick="location.href='{% url 'room:export_data' %}'" type="button" class="abc" value="Export">

    {% endif %}
  </div>
  <script type="text/javascript">
    window.addEventListener( "pageshow", function ( event )
    {
      var historyTraversal = event.persisted || (typeof window.performance != "undefined" && window.performance.navigation.type === 2);
      if( historyTraversal )
      {
        window.location.reload();
      }
    });
      $('#f1').click(function(){
        $('#load').css("visibility","visible");
        window.location.href = "{% url 'room:barak_room_list' %}";
      })
      $('#f2').click(function(){
        $('#load').css("visibility","visible");
        window.location.href = "{% url 'room:umiam_room_list' %}";
      })
  </script>
{% endblock %}